all:
  hosts:
    alp-k8s00201.alfa.local:
      ansible_host: 172.20.32.98
      ip: 172.20.32.98
      access_ip: 172.20.32.98
      node_labels:
        px/enabled: "false"
    alp-k8s10201.alfa.local:
      ansible_host: 172.20.32.99
      ip: 172.20.32.99
      access_ip: 172.20.32.99
      node_labels:
        px/enabled: "false"
    alp-k8s20201.alfa.local:
      ansible_host: 172.20.32.100
      ip: 172.20.32.100
      access_ip: 172.20.32.100
      node_labels:
        px/enabled: "false"
    alp-k8s00203.alfa.local:
      ansible_host: 172.20.32.103
      ip: 172.20.32.103
      access_ip: 172.20.32.103
      node_labels:
        px/zone: onprem-dca
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
        px/ls: "true"
    alp-k8s10203.alfa.local:
      ansible_host: 172.20.32.104
      ip: 172.20.32.104
      access_ip: 172.20.32.104
      node_labels:
        px/zone: onprem-dcb
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
        px/ls: "true"
    alp-k8s20203.alfa.local:
      ansible_host: 172.20.32.105
      ip: 172.20.32.105
      access_ip: 172.20.32.105
      node_labels:
        px/zone: onprem-dcc
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
  children:
    kube-master:
      hosts:
        alp-k8s00201.alfa.local:
        alp-k8s10201.alfa.local:
        alp-k8s20201.alfa.local:
    kube-node:
      hosts:
        alp-k8s00201.alfa.local:
        alp-k8s10201.alfa.local:
        alp-k8s20201.alfa.local:
        alp-k8s00203.alfa.local:
        alp-k8s10203.alfa.local:
        alp-k8s20203.alfa.local:
    etcd:
      hosts:
        alp-k8s00201.alfa.local:
        alp-k8s10201.alfa.local:
        alp-k8s20201.alfa.local:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
