all:
  hosts:
    alt-k8s00501.alfa.local:
      ansible_host: 172.20.56.98
      ip: 172.20.56.98
      access_ip: 172.20.56.98
      node_labels:
        px/enabled: "false"
    alt-k8s00503.alfa.local:
      ansible_host: 172.20.56.103
      ip: 172.20.56.103
      access_ip: 172.20.56.103
      node_labels:
        px/zone: onprem-dca
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
    alt-k8s00504.alfa.local:
      ansible_host: 172.20.56.106
      ip: 172.20.56.106
      access_ip: 172.20.56.106
      node_labels:
        px/zone: onprem-dca
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s00505.alfa.local:
      ansible_host: 172.20.56.108
      ip: 172.20.56.108
      access_ip: 172.20.56.108
      node_labels:
        px/zone: onprem-dca
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s00506.alfa.local:
      ansible_host: 172.20.56.110
      ip: 172.20.56.110
      access_ip: 172.20.56.110
      node_labels:
        px/zone: onprem-dca
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s10501.alfa.local:
      ansible_host: 172.20.56.99
      ip: 172.20.56.99
      access_ip: 172.20.56.99
      node_labels:
        px/enabled: "false"
    alt-k8s10503.alfa.local:
      ansible_host: 172.20.56.104
      ip: 172.20.56.104
      access_ip: 172.20.56.104
      node_labels:
        px/zone: onprem-dcb
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
    alt-k8s10504.alfa.local:
      ansible_host: 172.20.56.107
      ip: 172.20.56.107
      access_ip: 172.20.56.107
      node_labels:
        px/zone: onprem-dcb
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s10505.alfa.local:
      ansible_host: 172.20.56.109
      ip: 172.20.56.109
      access_ip: 172.20.56.109
      node_labels:
        px/zone: onprem-dcb
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s10506.alfa.local:
      ansible_host: 172.20.56.111
      ip: 172.20.56.111
      access_ip: 172.20.56.111
      node_labels:
        px/zone: onprem-dcb
        px/region: onprem-1
        px/metadata-node: "false"
        px/enabled: "true"
    alt-k8s20501.alfa.local:
      ansible_host: 172.20.56.100
      ip: 172.20.56.100
      access_ip: 172.20.56.100
      node_labels:
        px/enabled: "false"
    alt-k8s20503.alfa.local:
      ansible_host: 172.20.56.105
      ip: 172.20.56.105
      access_ip: 172.20.56.105
      node_labels:
        px/zone: onprem-dcc
        px/region: onprem-1
        px/metadata-node: "true"
        px/enabled: "true"
      node_taints:
      - "zone=onprem-dcc:NoSchedule"
  children:
    kube-master:
      hosts:
        alt-k8s00501.alfa.local:
        alt-k8s10501.alfa.local:
        alt-k8s20501.alfa.local:
    kube-node:
      hosts:
        alt-k8s00503.alfa.local:
        alt-k8s00504.alfa.local:
        alt-k8s00505.alfa.local:
        alt-k8s00506.alfa.local:
        alt-k8s10503.alfa.local:
        alt-k8s10504.alfa.local:
        alt-k8s10505.alfa.local:
        alt-k8s10506.alfa.local:
        alt-k8s20503.alfa.local:
    etcd:
      hosts:
        alt-k8s00501.alfa.local:
          etcd_member_name: etcd1
        alt-k8s10501.alfa.local:
          etcd_member_name: etcd2
        alt-k8s20501.alfa.local:
          etcd_member_name: etcd3
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
